### ISSUE TITLE
Falta de instalador

### ISSUE THREAD

**Issue by agusstingalvan** [NicolasNocete/Rasti2.0-connect#5]
Cuando se quiere pasar el codigo desde el front, este falla, por falta del compilador de arduino.

{
    "error": "{'__stdout': '{\\n  \"compiler_out\": \"\",\\n  \"compiler_err\": \"\",\\n  \"builder_result\": null,\\n  \"upload_result\": null,\\n  \"success\": false,\\n  \"error\": \"Error during build: Platform \\'arduino:avr\\' not found: platform not installed\\\\nTry running `arduino-cli core install arduino:avr`\"\\n}', '__stderr': '', 'result': {'compiler_out': '', 'compiler_err': '', 'builder_result': None, 'upload_result': None, 'success': False, 'error': \"Error during build: Platform 'arduino:avr' not found: platform not installed\\nTry running `arduino-cli core install arduino:avr`\"}}",
    "message": "Internal Server Error",
    "success": false
}

Comando a ejecutar en la ruta raiz del repositorio: Solucion: arduino-cli core install arduino:avr
![image](https://github.com/NicolasNocete/Rasti2.0-connect/assets/50257259/4835efbb-46c9-4b79-827d-c27427be3418)

**Comment by NicolasNocete** [comment]
Se agrego al instalador la ejecucion del comando 
`arduino-cli core install arduino:avr`

**Comment by NicolasNocete** [comment]
![image](https://github.com/NicolasNocete/Rasti2.0-connect/assets/8340664/222c2358-2a51-4583-85b8-475e13feb3cb)
